#for defining constants for column lengths in models
USERNAME_LENGTH = 50
EMAIL_LENGTH = 70
PROFILE_PIC_LENGTH = 100
NAME_LENGTH = 100
PASSWORD_LENGTH = 50
POSITION_LENGTH = 50
LOGIN_TOKEN_LENGTH = 20
PUBLIC_ID_LENGTH = 20