#!/usr/bin/env bash
# Install packages for application to run
sudo apt update -y
sudo apt install python3-pip -y
sudo apt-get install pkg-config -y
sudo pip install pkgconfig -y
sudo apt install mysql-server -y
sudo apt-get install python3-dev -y
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install zlib1g-dev -y
sudo pip3 install mysqlclient

sudo pip3 install SQLAlchemy
sudo pip3 install Flask
sudo pip install flask-socketio
sudo pip install -U flask-cors
sudo pip install eventlet
pip install bcrypt

